/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'HARD RESET': '硬复位',
    'Export to clipboard': '导出到剪贴板',
    'Save': '保存',
    'You have': '你有',
    'Begin': '开始',
    'Changelog': '更新日志',
    'Play Again': '再玩一次',
    'Main Prestige Tree server': '主声望树',
    'Hotkeys': '快捷键',
    'Import': '导入',
    'oxygen': '氧气',
    'Currently': '当前',
    'MAINTENANCE': '维护',
    'Inventory': '库存',
    'You possess the following': '您拥有以下',
    'Introduction': '介绍',
    'You are ready to venture out.': '你准备好外出冒险了。',
    'Story': '故事',
    'Return and Rest': '返回和休息',
    'power': '能量',
    'Obtained Item!': '获得物品！',
    'CORRIDOR': '走廊',
    'Auxiliary Power Cable': '辅助电源线',
    'Fan Controls Locked Out': '风扇控制装置被锁定',
    'Fusebox Key': '保险丝盒钥匙',
    'Repair Circuit': '修复电路',
    'Grab Fusebox Key': '抓住保险丝盒钥匙',
    '[OXYGEN DEPLETING]': '[氧气消耗中]',
    'FUSEBOX': '保险丝盒',
    'Fusebox': '保险丝盒',
    'Overview': '概览',
    'Oxygen': '氧气',
    'Tasks': '任务',
    '[REFILLING OXYGEN]': '[重新充氧]',
    'Clogged Garbage Disposal': '垃圾堵塞处理',
    'Damaged Overhead Vent': '损坏的架空通风管',
    'Grab Loose Wires': '抓住松散的电线',
    'Lock Reprogrammer Station': '锁重编程器站',
    'Remove Fuse from Wall': '从墙上取下保险丝',
    'Fuse': '保险丝',
    'Scan Lock': '扫描锁',
    'What\'s in the vent?': '通风口里有什么?',
    'TreeQuest': '任务树',
    'P: open Personal menu': 'P:打开个人菜单',
    'M: Return to the Maintenance room': 'M:回到维修室',
    'H: open Help menu': 'H:打开帮助菜单',
    'The key to the fusebox in the Maintenance room.': '维护室保险丝盒的钥匙。',
    'A handheld lock scanning device, only usable within the central corridor.': '手持式锁定扫描设备，仅在中央走廊内使用。',
    'You can see something in the vent, but the steel cover is firmly in place...': '你可以看到通风口里有东西，但钢盖纹丝不动……',
    ' Whoever was here before you was trying to crack the lock on the filtration circuit box, but it looks like they fled or worse before they had a chance to finish the job.': '在你之前来的人试图打开过滤电路盒的锁，但看起来他们在有机会完成任务之前就逃走了，甚至更糟。',
    ' There\'s an auxiliary power socket near the section to the south, that looks to still be in working order.': '在南边的部分有一个备用电源插座，看起来还能正常工作。',
    ' The source  of the atmospheric issues seems to be here. Toxic air is seeping in through the ventilation system, which is still pumping the fumes in despite the lack of power.': '大气问题的源头似乎就在这里。有毒空气正通过通风系统渗透进来，尽管没有动力，通风系统仍在将浓烟吸入室内。',
    ' The outer wall of the corridor is beginning to cave in, but it seems stable for the time being. The ground level vent and its override controls are still accessible, at a stretch.': '走廊的外墙开始塌陷，但目前看起来还算稳定。地面的通风口和它的超驰控制系统仍然可以使用。',
    ' The filtration system seems to be functional, and garbage control looks intact, though it would need additional power to function. All other systems are offline.': '过滤系统似乎还能正常工作，垃圾控制看起来也完好无损，不过它需要额外的动力才能发挥作用。所有其他系统都处于离线状态。',
    'The garbage disposal is jammed, by what appears to be a metal tank.': '垃圾处理机被一个金属罐子堵住了。',
    ' Many of the maintenance terminals in this section have been damaged - one in particular lies open, its innards exposed.': '这一区域的许多维护终端都已损坏，其中有一个终端是敞开的，其内部暴露在外。',
    'The vents in Corridors 3 and 7 are now open.': '3号和7号走廊的通风口已经打开。',
    'Unpowered Maintenance Terminal': '无动力维护终端',
    'Retrieve Fuse': '检索保险丝',
    'Pick up Reprogrammer': '拾取重编程器',
    'Override Filtration System': '覆盖过滤系统',
    'Open the side vents': '打开侧通风口',
    'Lock Reprogrammer': '锁定重新编程',
    'Filtration System Overridden': '过滤系统被覆盖',
    'Emergency System Circuit Box': '应急系统电路箱',
    'Auxiliary Power Inlet': '辅助电源入口',
    'A blank maintenance terminal, connected to an auxiliary power socket in Corridor 7.': '一个空白的维护终端,连接到一个辅助电源插座在走廊7中。',
    ' One of the overhead bulbs blinks out intermittently, distracting your eye. Otherwise, this section of corridor is quite intact.': '头顶上的一个灯泡会断断续续地闪烁，分散你的注意力。除此之外，这段走廊还是很完整的。',
    ' An electronic supply closet lies on the floor. Presumably someone was working here recently, before the incident.': '地板上有一个电子用品柜。应该有人最近在这里工作，就在事故发生之前。',
    'You are holding the live wires from the wall.': '您正在从墙上握住火线。',
    'The anti-tamper system has kicked in. You will need to wait or cycle power to the corridor to reset it.': '防篡改系统已经启动了。您将需要等待或循环电源到走廊重置它。',
    'The anti-tamper system has been bypassed.': '防破坏系统被绕过了。',
    'Locked Electronics Closet': '上锁的电器柜',
    'Bypass Tamper Security': '绕过防篡改安保',
    'A closet containing spare electrical components. The lock resets whenever the power is cycled.': '装有备用电器元件的壁橱。每当电源循环时，锁就会重置。',
    ' There\'s a massive hole in the ventilation pipe running above the northern corridors. It\'s not large enough to climb into, but you could reach up or feed something through.': '北部走廊上方的通风管道上有个大洞。它不够大，爬不进去，但你可以够到上面，或者塞东西进去。',
    ' The southeast corner of the corridor has suffered massive structural damage. The wall has crumbled away, revealing exposed, sparking wires.': '走廊的东南角已经遭受了大规模的结构破坏。墙塌了，露出了暴露的、冒着火花的电线。',
    ' The northeast corner of the corridor is in quite poor condition. The floor has been torn up in places and your footing is uneven.': '走廊的东北角条件很差。地板有几处被撕裂了，你只能踉跄行走。',
    ' The ground level vent in the east wall looks to be in decent condition.': '东墙的地面通风口看起来状况良好。',
    ' The key reprogrammer terminal has fallen against the inner wall. It\'s on its side but still seems to be functioning perfectly.': '关键的重编程终端从内壁掉落下来，倒在一边，但似乎仍然运作得很完美。',
    ' The garbage disposal unit on the eastern wall has seen better days, but should still operate in theory.': '东墙上的垃圾处理装置虽然风光不再，但理论上应该还能运作。',
    ' The eastern side of the corridor has been mostly untouched by the incident. There are superficial issues with the walls but nothing compromising.': '该走廊的东侧几乎未受该事件影响。墙壁有一些表面的问题，但没有任何妥协。',
    ' A circuit board ordinarily obscured by a panel is exposed as well - perhaps you can salvage something from it.': '通常被嵌板遮挡的电路板也会暴露出来——也许你可以从中抢救出一些东西。',
    ' Now you have the key to the fusebox, you can power other sections of the corridor. Hopefully you can find more fuses, and repair the life support system.': '现在你有了保险丝盒的钥匙，你可以给走廊的其他部分供电。希望你能找到更多保险丝，修复生命维持系统。',
    'is a puzzle-adventure game using The Modding Tree as an engine. Whilst there will [eventually] (meaning in later updates) be incremental features, a key gameplay component is (and will still be) exploration.': '是一款使用Modding树作为引擎的益智冒险游戏。虽然最终会出现(游戏邦注:即在之后的更新中)增量功能，但一个关键的游戏玩法组件是(并将仍然是)探索。',
    'Your primary resource in this game is your oxygen level. This number is an abstraction that represents the number of seconds you can spend outside the safe zone (whilst still allowing for you to return to safety afterwards).': '你在游戏中的主要资源是你的氧气水平。这个数字是一个抽象的数字，代表你可以在安全区域之外花费的秒数(同时也允许你在之后回到安全区域)。',
    'Your primary aim when enturing outside of the safe zone is to complete tasks. These tasks are represented in the form of buyables, and will all behave in a similar way. Tasks are colour-coded for easy recognition, as below': '当你冒险离开安全区时，你的主要目标是完成任务。这些任务以可购买的形式表示，并且都将以类似的方式运行。如下图所示，为了便于识别，任务用颜色编码',
    'Your objective will vary, but can always be found in the \'Personal\' node (the P in the side list). This tab contains various help topics, more of which will [eventually] be added as you progress.': '你的目标会有所不同，但总是可以在“个人”节点(侧栏的 P)中找到。此选项卡包含各种帮助主题，随着您的进展，将[最终]添加更多的帮助主题。',
    'You start with one fuse, in the Corridor 1 slot. You can click to remove this fuse, which will then allow you to place it in another corridor. As you find additional fuses, you can power multiple sections at once.': '你从走廊1号槽的一个保险丝开始。你可以点击来移除这个保险丝，这将允许你把它放在另一个走廊。当你发现额外的保险丝时，你可以一次为多个部分供电。',
    'You start the game with one oxygen tank, granting you a total of ten seconds\' venturing time. Finding additional tanks will increase this limit. [Eventually,] you may have the option to improve its efficiency.': '游戏一开始你只有一个氧气罐，总共给你10秒的冒险时间。找到额外的储罐会增加这个限制。[最终]你可以选择提高它的效率。',
    'You can only venture in powered sections. You can change which sections are powered whilst still in \'venture\' mode, but most tasks will reset if their section is powered off, or be uncompletable if a preceding section is. (There are exceptions to this. Whilst not required, they will let you \'sequence break\', so feel free to experiment!': '你只能在动力区里冒险。在“冒险”模式下，你可以改变哪个部分是通电的，但大多数任务会在断电后重置，或者在前一个部分断电后无法完成。(这也有例外。虽然不是必需的，但它们会让你“打破序列”，所以你可以自由尝试!',
    'When you venture out of safety and perform tasks, the oxygen level will decrease. Once it hits zero, you will need to return to the safe zone, where your oxygen will automatically refill.': '当你冒险离开安全地带去执行任务时，体内的氧气含量会下降。一旦它达到零，你就需要回到安全区域，在那里你的氧气会自动补充。',
    'The fusebox allows you to control power to the eight corridor sections around the central maintenance room. Each room is represented by a slot on the grid.': '通过保险丝盒控制中央维护室周围8个走廊段的电源。每个房间都由网格上的一个槽表示。',
    'The \'nodes\' on the main screen represent a map of the area you\'re in, as though viewed from above - each node is a room or a part of an area, and may contain items or tasks to complete.': '主屏幕上的“节点”代表你所处区域的地图，就像从上面看一样——每个节点是一个房间或一个区域的一部分，可能包含需要完成的项目或任务。',
    'Tasks that remain visible and green will have one or more related tasks to complete. In many cases, they will reset if you run out of oxygen or stop venturing out, so you will need to plan your route to ensure you can complete all the required tasks.': '保持可见和绿色的任务将有一个或多个相关的任务要完成。在很多情况下，如果你没有氧气或停止冒险，它们会重置，所以你需要计划你的路线，以确保你可以完成所有需要的任务。',
    'Tasks take your entire focus, so only one can be completed at a time - starting a task will turn the others in the area red. In addition, if you leave the area before a task has been completed, your progress will be lost!': '任务占用了你全部的注意力，所以一次只能完成一项任务——启动一项任务会使区域内的其他任务变成红色。此外，如果您在任务完成之前离开该区域，您的进度将丢失!',
    'Red: this task cannot be completed right now. This usually means you lack a necessary item or a pre-requisite task has not yet been completed. The text will usually give you an indication of what you need to do first.': '红色:此任务目前无法完成。这通常意味着你缺少一个必要的项目，或者一个先决的任务还没有完成。文本通常会提示你首先需要做什么。',
    'Once a task is completely finished with (if the task is stand-alone, or the final related task in the chain has been completed) its icon will disappear completely. Usually you will receive an item or [eventually] the gameplay will change in some way.': '一旦一个任务完全完成(如果该任务是独立的，或者链中的最终相关任务已经完成)，它的图标将完全消失。通常情况下，你会收到一个道具，或者游戏玩法会发生某些改变。',
    'Note: Use of [eventually] in these pages hints at functionality planned for a later update.': '注意：在这些页面中使用[最终]暗示了计划用于以后更新的功能。',
    'Green: this task has been completed. It remains visible, usually with a hint to a subsequent task it enables you to complete.': '绿色:任务已完成。它仍然是可见的，通常会提示您完成后续任务。',
    'Amber: this task is available to be completed. The description will state what the task will do and provide a duration in seconds. Once you begin the task it will fill green to show its progress.': '琥珀色:这个任务可以被完成。描述将说明任务将做什么，并提供以秒为单位的持续时间。一旦你开始这个任务，它就会填充绿色来显示它的进度。',
    'You have no fuses to place in this slot.': '这个槽里没有保险丝。',
    'You can venture out again once your reserves have refilled.': '一旦你的储备又满了，你可以再次外出探险。',
    'You are out of oxygen - return to the Maintenance room!': '您没有氧气了-返回维护室！',
    ' A single fluorescent bulb flickers overhead, illuminating the northern section of the corridor. Rubble lines the floor - it seems part of the ceiling has collapsed here.': '一个荧光灯在头顶闪烁，照亮了走廊的北部。地板上布满了碎石，看起来天花板的一部分已经塌了。',
    ' A panel on the north wall controls the overhead ventilation fans. Beside it, lower down, is an auxiliary power cable - it should provide enough charge to power one system.': '北墙上的面板控制着上方的通风机。在它旁边，往下，是一条辅助电力电缆-它应该能提供足够的电量给一个系统供电。',
    ' A filing cabinet, once inside the maintenance room, lies on the floor, its contents spilled out.': '档案柜，一进入维修室，就倒在地板上，里面的东西全都洒了出来。',
    'Close the doors, and wait for oxygen to replenish.': '关上门，等待氧气补充。',
    'Your oxygen is steadily depleting. You will be forced to return here once it empties.': '你的氧气正在逐渐消耗。等它空了，你就得回到这里。',
    '1 oxygen tank, granting 10 seconds of exploration time.': '1个氧气瓶，给予10秒的探索时间。',
    'You\'ve reached the end of the "prologue".': '您已经到达“序幕”的结尾。',
    'Venture Out': '外出冒险',
    'Power and repair the life support system in all eight corridors to activate it.': '通电并维修所有八个走廊的生命支持系统，以将其激活。',
    'If you didn\'t already, try completing the game with only two oxygen tanks! You\'ll have to be a little creative to manage it in time.': '如果您还没有，请尝试仅使用两个氧气瓶来完成游戏！ 您必须要有一点创意才能及时进行管理。',
    'Open the door. Oxygen will steadily deplete.': '打开门。 氧气将稳步耗尽。',
    'Congrats on skipping one of the oxygen tanks! Did you do so intentionally?': '恭喜您跳过其中一个氧气瓶！ 您是故意这样做的吗？',
    'Hopefully the gameplay is intuitive. If not, check the Help (H) layer, or press H on the keyboard, for assistance.': '希望游戏玩法是直观的。 如果不是，请检查“帮助”（H）层，或按键盘上的H以获取帮助。',
    'There\'s no offline progress, and early parts of the game are time-sensitive.': '没有离线进度，并且游戏的早期部分对时间敏感。',
    'The next layers aren\'t properly implemented so you can\'t "keep going", but you\'re welcome to play again.': '下一层没有正确实现，因此您不能“继续前进”，但是欢迎您再次玩。',
    'This should be considered a prologue/demo - there\'s a fixed amount of gameplay.': '这应该被认为是一个序言/演示-有一个固定的数量的游戏。',
    'This mod is closer in parts to an adventure/puzzle game than an incremental. (As it stands, there are no incremental features yet': '这个mod在某种程度上更接近冒险/谜题游戏，而不是增量游戏。(目前，还没有增量的特性',
    'Loading... (If this takes too long it means there was a serious error!': '加载中……(如果花费时间过长，说明有很严重的错误发生了!)',
    "Feel free to contact me on Discord (via either of the Modding Tree servers) for assistance, suggestions or bug reports - any input is appreciated!": "请随时通过 Discord（通过任一 Modding Tree 服务器）与我联系以获取帮助、建议或错误报告 - 感谢任何来信！",
    "Loading... (If this takes too long it means there was a serious error!)←": "加载中……(如果花费时间过长，说明有很严重的错误发生了!)←",
    "NOTE: saves from the DEV version are incompatible with this version.": "注意：来自开发版本的存档与此版本不兼容。",
    "The Modding Tree\n\t\t\t\t\t\t\tDiscord": "The Modding Tree\n\t\t\t\t\t\t\tDiscord",
    "Time splits": "时间分割",
    "0.2.1-SR - Generations/Historia": "0.2.1-SR - 世代/历史",
    "\"Glad to hear it! In that case, we'll go ahead and get you started. Look up, please.\" The moment you glance upwards, a bright flash fills your eyes - as it fades you see the lens of a camera pointing down at you. \"That's perfect. I'll get your ID printed for you now, it'll just take a few minutes.\"": "\“很高兴听到它！那样的话，我们会继续让你开始。请抬头看。\”当你向上瞥一眼时，一道明亮的闪光充满了你的眼睛——随着它逐渐消失，你看到一个镜头 相机向下指着你。 \"那太好了。我现在就帮你打印你的身份证，只需几分钟。\"",
    "\"Welcome! You must be the new maintenance contractor, right?\" The receptionist beckons you over to the desk, whilst flicking through a stack of papers. \"Heard you ran into a little trouble on the way in, hope you're feeling alright. If you need I can have you taken to the sickbay.\" You dismiss the concerns - you feel fine, a little shaken at most.": "\“欢迎！你一定是新的维修承包商吧？\” 接待员招手让你走到办公桌前，一边翻着一叠文件。 \“听说你在进来的路上遇到了点小麻烦，希望你感觉还好。如果你需要，我可以带你去病房。\”你打消了这些顾虑——你感觉很好，最多有点动摇。",
    "A keyhole next to the 'BF' button. It likely controls access to that floor.": "“BF”按钮旁边的钥匙孔。 它可能控制对该楼层的访问。",
    "A largely featureless corridor, connecting the Reception and the central elevator. Bathrooms lead off from either side, and pots of decorative greenery fill the corners.": "一条平平无奇的走廊，连接接待处和中央电梯。 两侧通向清洗室，角落里堆满了装饰性的绿色植物。",
    "BF Key Slot": "BF 钥匙插槽",
    "Blank": "空白",
    "DECONTAMINATI": "净化室",
    "FLOOR": "楼层",
    "Help": "帮助",
    "I am a button!": "我是一个按钮！",
    "In the meantime, why don't you get changed out of your flight gear? There's a new uniform ready for you, locker... #44. Just head up the elevator to the third floor, and follow the signs for the Lambda Division labs. You can clean yourself up in the decontamination pods too, I'm sure they won't mind.\"": "与此同时，你为什么不换掉你的飞行装备呢？ 有一套新制服为你准备好了，储物柜......#44。 只需乘电梯到三楼，然后按照 Lambda 分部实验室的指示牌走即可。 你也可以在去污舱里清理自己，我相信他们不会介意的。”",
    "is a puzzle-adventure game using The Modding Tree as an engine. Whilst there may [eventually]  be incremental features, TreeQuest is at its heart a game about puzzles/exploration.": "是一款使用 The Modding Tree 作为引擎的解谜冒险游戏。 虽然可能 [最终] 增加功能，但 任务树 的核心是一个关于谜题/探索的游戏。",
    "MAIN ELEVATOR (": "主电梯（",
    "Museum": "博物馆",
    "Personal": "个人",
    "RECEPTI": "接收器",
    "Reception": "接待处",
    "Safe zone - oxygen will not decrease.": "安全区——氧气不会减少。",
    "Tasks that remain visible and green will have one or more related tasks to complete. Once a task is completely finished with (if the task is stand-alone, or the final related task in the chain has been completed) its icon will disappear completely. Usually you will receive an item or the gameplay will change in some way.": "保持可见和绿色的任务将有一项或多项相关任务需要完成。 一旦一个任务完全完成（如果任务是独立的，或者链中的最后一个相关任务已经完成）它的图标将完全消失。 通常你会收到一个物品，或者游戏玩法会以某种方式改变。",
    "The 'nodes' on the main screen represent a map of the area you're in, usually as though viewed from above - each node is a room or a part of an area, and may contain items or tasks to complete.": "主屏幕上的“节点”代表您所在区域的地图，通常就像从上方查看一样 - 每个节点都是一个房间或一个区域的一部分，可能包含要完成的项目或任务。",
    "The entry to Reception looks to be a security door, the panel beside it reading \"SecLock LEVEL 1\". Normally it'd keep visitors from wandering into the building, but right now it's propped open.": "接待处的入口看起来是一扇安全门，旁边的面板上写着“安全锁 1 级”。 通常它会阻止游客进入建筑物，但现在它是开放的。",
    "The main central elevator for the facility. Currently on the second floor.": "设施的主要中央电梯。 目前停靠在二楼。",
    "The primary way to make progress is to complete tasks. These tasks are represented in the form of buyables, and will all behave in a similar way. Tasks are colour-coded for easy recognition, as below": "取得进展的主要方式是完成任务。 这些任务以可购买的形式表示，并且都以类似的方式运行。 任务用颜色编码以便于识别，如下所示",
    "The signposts outside the elevator read": "电梯外的路标上写着",
    "You've been given permission to visit the second and third floors for now - best not to go wandering elsewhere on your first day here.": "您现在已获准参观二楼和三楼 - 第一天最好不要去别处闲逛。",
    "Your inventory is currently empty.": "您的库存目前是空的。",
    "Your objective will vary, but can always be found in the 'Personal' node (the P in the side list). This tab contains various help topics, more of which will be added as you progress.": "您的目标会有所不同，但始终可以在“个人”节点（侧列表中的 P）中找到。 此选项卡包含各种帮助主题，随着您的进展，将添加更多帮助主题。",
    "A decontamination system, normally used for visitors to the laboratory. You'll need to undress before using it.": "一种净化系统，通常用于实验室访客。 您需要在使用前脱下衣服。",
    "Decontamination Chamber": "净化室",
    "Following the signs for Lambda Division leads you to a large white room. In the centre stands a row of decontamination units - the sort used to clean off radiation or microbes after visiting somewhere unknown.": "按照 Lambda 分区 的指示，您将进入一个白色的大房间。 中心是一排净化装置——用于在访问未知地方后清除辐射或微生物的那种。",
    "Laboratory": "实验室",
    "Loading Dock": "装货台",
    "On either side of the units are a set of lockers - presumably used for storing scientists' personal effects when they're working, and vice versa.": "单元的两侧是一组储物柜——大概用于存放科学家工作时的个人物品，反之亦然。",
    "Locker #": "储物柜#",
    "The main central elevator for the facility. Currently on the third floor.": "设施的主要中央电梯。 目前停靠在三楼。",
    "0 undefined to unlock (You have 0 undefined": "0 未知 去解锁（您有 0 未知",
    "The locker storing your flight suit and new maintenance uniform.": "存放飞行服和新维修制服的储物柜。",
    "\"Ah, hello again! I see you found the locker okay.\" The receptionist starts talking to you again as soon as you enter the room. \"We'll have someone clean your gear and take it up to your room, once one's assigned to you. Your supervisor will fill you in about all that, though.\"": "\“啊，你好！我看你找到储物柜了。\”你一进房间，接待员又开始和你说话。 \“一旦分配给你，我们就会有人清洁你的装备并将其带到你的房间。不过，你的主管会告诉你所有这些。\”",
    "\"For now, though...\" As though rehearsed, the printer spits out a card, your face featured prominently on the front. \"Here you go! Your ID is all ready. You don't have any access yet, so head straight down to Maintenance and your boss will get things sorted.\"": "\“现在，不过……\” 打印机好像排练过一样，吐出一张卡片，正面突出了你的脸。 \"你去吧！ID已经准备好了。你还没有任何访问权限，所以直接去维护，你的老板会把事情整理好。\"",
    "\"Oh, one more thing - here's the elevator key. You need this to get down to the basement.\" A nondescript key, with a red tag labelled 'BF', sits next to your ID on the table. \"You'd best get going now. Have a wonderful day!\"": "\“哦，还有一件事——这是电梯钥匙。你需要这个才能下到地下室。\”一把不起眼的钥匙，上面标着“BF”的红色标签，放在桌子上你的身份证旁边。 \“你最好现在就开始。祝你有美好的一天！\”",
    "Elevator Key": "电梯钥匙",
    "ID Card": "身份证",
    "Item Acquired": "物品获得",
    "BASEMENT FLOOR": "地下室",
    "The keyhole controlling access to BF. Your basement key is inserted.": "控制对 BF 访问的锁孔。 您的地下室钥匙已插入。",
    "You can now ride the elevator down to the basement floor.": "您现在可以乘坐电梯下到地下室。",
    "\"Quality maintenance is hard to find around there.\" That's apparently all the explanation HQ thought you needed, before shipping you off to a planet you'd never even heard of.\n        Six days later, your ship arrived nose-first a couple of miles from the site after a close shave with an asteroid belt. It's in no state to fly any time soon, but this is a year-long assignment, so you weren't too concerned.\n        You made your way to your residence- and workplace-to-be.": "\“那里急缺高质量的维修工。\”在把你送到一个你闻所未闻的星球之前，总部认为这就是你需要的所有解释。\n六天后，你的飞船在离事发地点几英里的地方与小行星带擦身而过。飞船暂时还不能起飞，还好这项任务长达一年，这使你放下了顾虑。\n你找到了你将来的住处和工作地点。",
    "After checking in past the guards, and changing out of your flight suit into your maintenance overalls, the receptionist sent you straight to the service elevator, to check in with the onsite officer in the basement office. You haven't had an introduction yet, no explanation as to where you were or what this company even did.": "在通过警卫办理登机手续后，将飞行服换上维修工作服，接待员将带您到服务电梯，与地下室办公室的现场人员办理登机手续。 你还没有介绍，没有解释你在哪里或者这家公司做了什么。",
    "As the elevator descended, what sounded like a rather concerning explosion shook the building. As it approached the bottom,  an odd smell filled the air and it became harder and harder for you to breathe.\n        Pulling your shirt up over your mouth, you darted out of the elevator the moment it reached the bottom. Toxic fumes were billowing into the room, and rubble was everywhere. Anyone who was working down here had presumably managed to flee before the explosion hit.\n        You managed to dive into the maintenance office - which, mercifully, still had clean air inside it - and seal the door behind you, before passing out.": "电梯下降时，听起来像是相当令人担忧的爆炸声震动了大楼。 当它接近底部时，一股奇怪的气味弥漫在空气中，你越来越难以呼吸。\n 拉起你的衬衫捂住嘴，在电梯到达底部的那一刻，你冲出电梯。 毒气滚滚进入房间，到处都是瓦砾。 在这里工作的任何人都可能在爆炸发生之前设法逃离。\n 你设法潜入维护办公室 - 幸运的是，里面仍然有干净的空气 - 并在昏倒之前将你身后的门密封。",
    "Descent": "下降",
    "Proceed": "前往",
    "Waiting seemed pointless, so you took a look through the schematics in the room. It looks as though the corridor surrounding this room houses the life support system - and if you could get that back online, you'd be able to set up some power generation from the components here.\n        You managed to piece together a basic respirator, and found a portable air tank you could take with you. It'd only let you stay out for a few moments but it should be enough to start working on repairs. Better than waiting for a rescue that might never come.": "等待似乎毫无意义，所以你查看了房间里的原理图。 看起来这个房间周围的走廊里有生命维持系统——如果你能把它恢复在线，你就可以用这里的组件来发电。\n你设法拼凑了一个基本的呼吸器 ，并找到了一个可以随身携带的便携式空气罐。 它只会让你在外面呆一会儿，但它应该足以开始维修。 总比等待可能永远不会到来的救援要好。",
    "When you came to, you surveyed the room. Most of the systems were offline, but a diagnostic panel was still functioning. From that you got a basic sense of the situation: power and life support to the building had failed after some kind of impact or explosion, and only basic systems were online.\n        The entirety of the staff had evacuated, leaving you alone in a facility you'd arrived at today...assuming this was even still the same day. To make matters worse, the facility had automatically locked the basement down to contain the issue, and without power lifting the blast doors would be impossible. You were trapped down here.": "当你来到时，你调查了房间。 大多数系统都处于离线状态，但诊断面板仍在运行。 从中你对情况有了一个基本的了解：在某种撞击或爆炸后，建筑物的电源和生命支持都失败了，只有基本系统在线。\n所有工作人员都撤离了，留下你一个人 你今天到达的设施......假设这仍然是同一天。 更糟糕的是，该设施已自动锁定地下室以控制问题，如果没有动力提升防爆门是不可能的。 你被困在这里。",
    "You have made a total of": "你总共做了",
    "Your best  is": "你最好的是",
    "A personal ID card, granting access to the facility.": "个人身份证，允许进入设施。",
    "Corridor": "走廊",
    "In-progress task chains may reset if you run out of oxygen or stop venturing out, so you will need to plan your route to ensure you can complete all required tasks in time.": "如果您的氧气用完或停止冒险，正在进行的任务链可能会重置，因此您需要规划路线以确保可以及时完成所有必需的任务。",
    "Maintenance": "维护",
    "Oxygen Tank": "氧气罐",
    "When you venture out of safety and perform tasks, the oxygen level will decrease. Once it hits zero, you will need to return to a safe zone, where your oxygen will automatically refill.": "当您冒险脱离安全并执行任务时，氧气水平会降低。 一旦达到零，您将需要返回安全区域，在那里您的氧气会自动补充。",
    "You start the game with one oxygen tank, granting you a total of ten seconds' venturing time. Finding additional tanks will increase this limit.": "带着一个氧气罐开始游戏，它会给你总共十秒钟的冒险时间。 寻找额外的气罐会增加这个限制。",
    "Your primary resource in this game is your oxygen level. This number is an abstraction that represents the number of seconds you can spend outside of safe zones (whilst still allowing for you to return to safety afterwards).": "你在这个游戏中的主要资源是你的氧气等级。 这个数字是一个抽象表示，代表您可以在安全区域之外花费的秒数（仍然允许您在氧气耗尽后返回安全区域）。",
    "Hazard zone - oxygen will deplete steadily.": "危险区 - 氧气会不断消耗。",
    "Now you have the key to the fusebox, you can power other sections of the corridor. Hopefully you can find more fuses, and repair the life support system.": "现在你有了保险丝盒的钥匙，你可以为走廊的其他部分供电。 希望你能找到更多的保险丝，并修复生命支持系统。",
    " ALL": " 全部",
    "Shift-Click to Toggle Tooltips: ": "按住 Shift 键单击以切换工具提示：",
    "Single-Tab Mode": "单标签模式",
    "Single-Tab Mode: AUTO": "单标签模式：自动",
    "Speedrun Mode: ": "速通模式：",
    "default": "默认",
    "1 fuse, all 1 of which are in use.": "1 个保险丝，所有 1 个都在使用中。",
    " A self-locking electronic supply closet lies on the floor. Presumably someone was working here recently, before the incident.": "自锁电子供应柜位于地板上。 据推测，在事件发生前不久，有人在这里工作过。",
    "The garbage disposal chute is jammed shut. It cannot be opened by hand.": "垃圾处理槽被卡住了。 不可能徒手打开。",
    "Activate Life Support": "激活生命支持",
    "The circuit has been fully repaired. Throw the switch and reactivate life support!": "电路已完全修复。 扔掉开关吧，然后重启生命维持系统！",
    "You can now explore the corridors without relying on oxygen reserves.": "您现在不需要氧气储备就可以探索走廊。",
    "Stability": "续航",
    "With a resounding CLUNK echoing around the corridors, the battered life support systems whirred back into life. Over the next few minutes, the miasma faded away, and before long the diagnostic sensors in Maintenance reported that air quality was back to normal.\n        Unfortunately, in repairing the life support systems, you'd had to repurpose a few too many critical components of the main generators.\n        Whilst systems on the lowest level were still working, most of the building - including the elevator - was still unpowered.": "走廊里回荡着响亮的“咔嚓”声，破败的生命维持系统呼啸着恢复了生机。 在接下来的几分钟里，瘴气消失了，不久维护中的诊断传感器报告空气质量恢复正常。\n 不幸的是，在修理生命支持系统时，你不得不重新利用一些太多的关键 主发电机的组件。\n 虽然最低层的系统仍在工作，但建筑物的大部分 - 包括电梯 - 仍然没有供电。",
    "You thoroughly explored the basement, but couldn't locate anything suitable to repair the generators. There were, though, a number of places of interest - disused facilities, that may prove useful if you could get them up and running again.\n        Your main priority at this point was to find help, either inside the facility or off-world. Nothing down here would help in that regard, so you'd need to make your way up the tower. You recalled seeing a large dish mounted near the top, likely a long-distance comms array - if you could reach that, you could get a message out to HQ, or anyone...": "你彻底探索了地下室，但找不到任何适合修理发电机的东西。 不过，有许多有趣的地方 - 废弃的设施，如果您能让它们重新启动并运行，这可能会被证明是有用的。\n此时您的首要任务是寻求帮助，无论是在设施内还是在世界外 . 在这方面，这里没有任何帮助，因此您需要爬上塔楼。 你记得看到安装在顶部附近的一个大盘子，可能是一个长距离通信阵列——如果你能到达那里，你可以向总部或任何人发送消息......",
    "A damaged power generator. It needs a replacement rotary motor to repair.": "损坏的发电机。 它需要更换旋转电机进行维修。",
    "A large part of the terminal appears to be missing. There are no signs of damage, but there is a conspicuous gap to one end. On the wall within the gap is some kind of interface - three large prongs, that would likely slide into the back of the missing device.": "终端的很大一部分似乎丢失了。 没有损坏的迹象，但一端有明显的缺口。 在缝隙内的墙上是某种接口 - 三个大尖头，可能会滑入丢失设备的背面。",
    "A network interface of sorts, with three prongs in the shape of a triangle. Something should fit here...": "一系列网络接口，带有三角形的三芯插头。应该有某物与它契合......",
    "A wall-mounted terminal dominates most of this room, with a single wide screen spanning from corner to corner. Wires trail across the floor to what resembles a dentist's chair in the centre of the room, connecting to an oversized headset built in to the chair. Both the terminal and the headset are completely unresponsive": "壁挂式终端占据了这个房间的大部分，从一个角落到另一个角落都有一个宽屏幕。 电线穿过地板，到达房间中央类似于牙医椅子的地方，连接到椅子内置的超大耳机。 终端和耳机都完全没有反应",
    "After reactivating life support, you took some time to explore the maintenance room. It appears this room serves as some form of central control for power and other critical systems.\n            For now, as life support appears to be stable, you turned your focus to power generation.": "重新启动生命维持系统后，你花了一些时间探索维修室。 这个房间似乎是对电力和其他关键系统的某种形式的中央控制。\n 目前，由于生命支持似乎稳定，你将注意力转向发电。",
    "An empty set of maintenance mountings, designed for use with a range of Exosuit models.": "一套空的维护支架，设计用于一系列 强化外骨骼装甲 型号。",
    "Average power output": "平均功率输出",
    "Broken Generator": "损坏的发电机",
    "Click to turn ON.": "点击开启。",
    "Climb the shaft to": "爬上竖井到",
    "Current efficiency": "当前效率",
    "East Doorway": "东门",
    "EAST DOORWAY": "东门",
    "Empty Mountings": "空架子",
    "Enter the Elevator": "进入电梯",
    "Exit the Elevator": "离开电梯",
    "Exosuit required for safe traversal.": "安全穿越所需的强化外骨骼装甲。",
    "Exterior atmospheric conditions are rated": "外部大气条件是额定的",
    "From what you understand, the installation can produce its own power from a series of eight generators daisy-chained together. Between the damage to the building, and your own repairs to life support, the generators are functionally limited at best and outright broken at worst.\n            If you can repair a couple of the generators, you should be able to produce a stable loop, though it'd only provide enough power for the first couple of floors of an installation this size.": "据您所知，该装置可以通过菊花链连接在一起的八台发电机产生自己的电力。 在建筑物损坏和您自己维修生命维持系统之间，发电机的功能充其量是有限的，最坏的情况是完全损坏。\n 如果您可以修理几台发电机，您应该能够产生一个稳定的循环， 尽管它只能为这种尺寸的装置的前几层提供足够的电力。",
    "Generator": "发电机",
    "GENERATOR": "发电机",
    "Generator effect: Power -": "发电机效果：功率-",
    "Generator effect: Power +5, then *": "发电机效果：功率+5，然后*",
    "basic": "基础",
    "broken": "坏掉",
    "Last power output": "最后功率输出",
    "LOG": "日志",
    "Main Control": "主控",
    "MAIN CONTROL": "主控",
    "Main Elevator": "主电梯",
    "MAIN ELEVATOR": "主电梯",
    "Network Interface": "网络接口",
    "NETWORK INTERFACE": "网络接口",
    "Network Interface?": "网络接口？",
    "North Doorway": "北门",
    "NORTH DOORWAY": "北门",
    "OFFLINE": "离线",
    "Overheating Generator": "过热发电机",
    "Secluded Mountings": "隐蔽支架",
    "SECLUDED MOUNTINGS": "隐蔽支架",
    "South Doorway": "南门",
    "SOUTH DOORWAY": "南门",
    "The emergency ladder has been raised to 1F.": "应急梯已升至1层。",
    "The generator is only partly functional - one of the electronic relays has burnt out.": "发电机只是部分功能 - 其中一个电子继电器烧坏了。",
    "The generator loop is currently": "发电机循环目前是",
    "The lockdown has been lifted, and the elevator doors lie open. You should be able to make your way back up the facility, this way - but with power at a premium, you'll only be able to ride it partway up.": "封锁已经解除，电梯门敞开着。 您应该能够以这种方式返回该设施 - 但由于动力不足，您只能将其骑到一半。",
    "The main central elevator for the installation. With the current level of power, the elevator cannot move from the basement floor.": "设施的主要中央电梯。 以目前的功率水平，电梯无法从地下室移动。",
    "There's an emergency hatch on the roof of the elevator, with a small ladder you can extend upwards from it. It should be high enough to scale one extra floor if need be.": "电梯顶上有一个应急舱口，上面有一个小梯子可以伸缩。要到达更高一层应该足够了",
    "This generator is missing a voltage regulator, now part of the life support system.": "这台发电机缺少电压调节器，现在是生命支持系统的一部分。",
    "This generator looks incomplete - the alternator is missing.": "这个发电机似乎不完整——交流发电机不见了。",
    "This generator overheats when running. It appears the evaporator coil is missing.": "该发电机在运行时会过热。 蒸发器盘管似乎丢失了。",
    "This room appears to be a maintenance bay of some kind. In the centre of the room stands a set of mounting points, for a heavy-duty exosuit, and surrounding it are robotic arms sporting a range of tools, currently lying dormant.\n                This was probably a place for quick repairs or loadout changes to maintenance staff's exosuits, but there's no equipment around to maintain right now...": "这个房间似乎是某种维修间。 房间中央有一组安装点，用于安装强化外骨骼装甲，周围是机械臂，上面装有各种工具，目前处于休眠状态。\n 这可能是快速修理或更换装备的地方 维修人员的外装，但现在周围没有设备可以维修……",
    "Unfinished Generator": "未完成的发电机",
    "WARNING": "警告",
    "West Doorway": "西门",
    "WEST DOORWAY": "西门",
    "(unpowered": "（无动力",
    "A heavy steel door. Without power it would need to be held open.": "一扇沉重的钢门。 如果没有电源，它需要持续的支撑才能打开。",
    "A terminal with a card swipe slot. It's currently unresponsive.": "带有刷卡槽的终端。 它目前没有响应。",
    "An imposing door, clearly branded SECLOCK, blocks entry into the office itself. It's locked tightly and won't budge.": "一扇气势宏伟的门，清楚地标有 密码锁，阻止进入办公室本身。 它被紧紧锁定，不会动。",
    "Damaged Fan": "损坏的风扇",
    "Insufficient Authorisation": "权限不足",
    "Post Room": "邮局",
    "Rotary Motor": "旋转电机",
    "Security": "安保",
    "Steel Doorway": "钢质门口",
    "The signposts for Security lead to this room - what appears to be a waiting room outside the security office proper, perhaps to keep visitors from seeing sensitive information?\n            There's little outside, but a few chairs and a damaged upright fan.": "保安指示牌通向这个房间——这似乎是保安办公室外的等候室，也许是为了防止访客看到敏感信息？\n 外面器物很少，只有几把椅子和一个损坏的立式风扇。",
    "Unpowered Terminal": "无动力终端",
    "VESTIBULE": "前厅",
    "You've climbed up the emergency ladder to this floor. The next floor up is out of reach - you'd need to restore more power to the elevator, and ride it higher, to proceed upwards.": "你已经爬上应急梯，到达这层楼了。 上一层遥不可及 - 您需要为电梯恢复更多电力，并将其升高高，才能继续向上。",
    "3 oxygen tanks, granting 30 seconds of exploration time.": "3 个氧气罐，提供 30 秒的探索时间。",
    "A handheld lock scanning device.": "手持锁扫描设备。",
    "A rotary motor, salvaged from a broken fan.": "从损坏的风扇中抢救出来的旋转电机。",
    "[Eventually], you will be able to swap out or improve generators to improve overall power generation.": "[最终]，您将能够更换或改进发电机以提高整体发电量。",
    "Generators": "发电机",
    "In the Vertical Map you'll find items that unlock/activate nodes on the 'normal' map. As the game proceeds it'll be worth revisiting regularly.": "在垂直地图中，您将找到解锁/激活“正常”地图上的节点的物品。 随着游戏的进行，值得定期重温。",
    "Nodes on the tree require a certain amount of power (see the Generators tab) to be 'powered' - below this level, they will be 'unpowered'. Nodes will behave differently based on whether or not they're powered, so you may need to increase your power output (or maybe even decrease it!) in order to proceed.": "树上的节点需要一定量的电力（参见发电机选项卡）才能“通电” - 低于此级别，它们将“未通电”。 节点的行为会根据它们是否通电而有所不同，因此您可能需要增加输出功率（甚至可能减少输出功率！）才能继续。",
    "Once you've activated the life support, you'll be able to access the Vertical Map, through the Main Elevator (ME) node. This will swap the tree from a top-down view of the basement, into a side-on view of the facility as a whole. Most nodes on the Vertical Map will be hidden, until you move into an adjacent node.": "激活生命支持后，您将能够通过主电梯 (ME) 节点访问垂直地图。 这会将树从地下室的自上而下视图转换为整个设施的侧视图。 垂直地图上的大多数节点将被隐藏，直到您移动到相邻节点。",
    "The eight generators (one each in nodes G1 through G8) will produce power when active. Each generator takes the power output from the previous one and performs some function to it, after a deduction for inefficiency. If a stable loop is formed - that is, if a generator has the same amount of power after a full loop - the average power level of all 8 generators will appear as the output in the MC layer.": "八台发电机（节点 G1 到 G8 各一台）将在活动时发电。 每个发电机从前一个发电机中获取功率输出，并在扣除低效率后对其执行某些功能。 如果形成了一个稳定的循环——也就是说，如果一个发电机在一个完整的循环后具有相同的功率——所有 8 个发电机的平均功率水平将作为 MC 层的输出出现。",
    "Vertical Map": "垂直地图",
    "You can toggle the generators on (or off) from the MC layer. This will kickstart the generators by feeding 100 power into generator 1. However, as five of the generators start broken, you won't be able to make a stable loop, so they'll switch back off again. By exploring further you'll be able to repair some/all of the generators, and produce power.": "您可以从 MC 层打开（或关闭）发生器。 这将通过向发电机 1 提供 100 电力来启动发电机。但是，当其中五个发电机开始损坏时，您将无法建立稳定的循环，因此它们将再次关闭。 通过进一步探索，您将能够修理部分/所有发电机并发电。",
    "[DEADLY]": "[致命]",
    "ONLINE": "在线",
    "Click to turn OFF.": "单击以关闭。",
    "A small supply room, off the side of the main post room. There are shelves on either side, lined with boxes of envelopes, address labels, stamps...nothing out of the ordinary.\n        A steady stream of water is flowing out of an air conditioning unit high on one wall. The floor is covered - but as the power to this room is still off, it's safe to traverse.": "一个小型供应室，位于主邮局旁边。 两边都有架子，里面摆满了信封盒、地址标签、邮票……没什么特别的。\n 一股源源不断的水从墙上的空调装置中流出。 地板被盖住了——但由于这个房间的电源仍然关闭，所以可以安全穿越。",
    "An audible sparking can be heard from the next room - the flooded floor is electrified, and unsafe to walk through whilst the power is on.": "隔壁房间传来可听见的火花——被淹的地板带电，在通电时穿过是不安全的。",
    "Broken Air Conditioner": "坏掉的空调",
    "Broken Security Door": "坏掉的防盗门",
    "ENTRYWAY": "出入口",
    "Exosuit Display": "强化外骨骼装甲架",
    "Handheld Jack": "手持式千斤顶",
    "MUSEUM": "博物馆",
    "POST ROOM": "邮局",
    "POST STORAGE": "邮政储蓄",
    "Pry open the door to": "撬开门到",
    "Remove the jack from the 1R door.": "从 1R 门上取下千斤顶。",
    "Search Toolbox": "搜索工具箱",
    "Screwdriver": "螺丝刀",
    "SecLock Terminal": "安全锁终端",
    "Slide the big crate to": "将大板条箱滑到",
    "The corridor is about as empty as before. One of the potted plants has been knocked over, in the rush to escape. One of the bathrooms is leaking water out into the hallway.": "走廊和以前一样空荡荡。匆忙逃生的人撞倒了一盆盆栽。 一间浴室正往走廊漏水。",
    "The corridor leading up to the museum. What would be a quite impressive-looking arch frames the path inside...would be, that is, if it wasn't currently in pieces.\n        Scaffolding surrounds what's left of the feature, with tools and the odd hard-hat scattered around the floor. It looks as though this reconstruction had been going on for a while before you arrived.": "通往博物馆的走廊。 什么会是一个非常令人印象深刻的拱门框架内部的路径......也就是说，如果它当前不是碎片。\n 脚手架围绕着特征的剩余部分，工具和奇怪的安全帽散落 在地板周围。 在您到达之前，这种重建工作似乎已经进行了一段时间。",
    "The door is damaged, you can see through it but you'll need force to pull it open.": "门坏了，你可以透过缝隙观察，但需要外力才能把它拉开。",
    "The door is only jacked up enough for you to slip through. The box is far too large to fit.": "门被顶起来，足以让你钻过。 但盒子太大，无法通过。",
    "The emergency ladder has been raised to 2F.": "应急梯已升至2层。",
    "The first room off the eastern corridor looks to be a depot for post. The incoming pile has a few items of junk mail, all addressed to the building. The outgoing pile is empty.\n            An inspection of the room doesn't reveal any useful documentation - no manifests, or shipping logs, or even delivery or pickup schedules.": "东边走廊的第一个房间看起来是一个邮局。 收到的一堆垃圾邮件有几封邮件，都是寄给大楼的。 输出堆是空的。\n 检查房间并没有发现任何有用的文件 - 没有清单，或运输日志，甚至没有交付或取货时间表。",
    "The main central elevator for the installation. With the current level of power, the elevator can go as high as 1F.": "设施的主要中央电梯。 以目前的功率等级，电梯可以上到1层。",
    "The SecLock door blocks the way - no longer propped open, but considerably bent out of shape.": "密码锁 门挡住了路——不再撑开，但明显弯曲变形。",
    "The sole remaining exhibit is a rather large Exosuit in the centre of the room.": "唯一剩下的展品是房间中央的一个相当大的 强化外骨骼装甲。",
    "There's a Model #### Exosuit in the centre of the area. Four metal claws are holding it in place.": "该区域的中心有一个模型#### 强化外骨骼装甲。 四个金属爪将其固定到位。",
    "This wing touts itself as a museum, a monument to the work done at this facility. Unfortunately it's currently a monument to opportunism - almost every exhibit in the room has been taken. That, or the facility's work revolves around empty, damaged displays. The information panels by the exhibits lie dormant and unpowered.": "这个侧翼自诩为博物馆，是对在该设施所做工作的纪念碑。 不幸的是，它目前是机会主义的纪念碑——房间里几乎所有的展品都被拿走了。 那，或者说设施的工作围绕着空的、损坏的显示器展开。 展品旁的信息面板处于休眠状态且未通电。",
    "Your current clearance (LEVEL 0) is insufficient for this terminal (LEVEL 1).": "您当前的许可（等级 0）对于这个终端（等级 1）是不够的。",
    "Slide the big crate to 1>": "将大板条箱滑到 1>",
    "Evaporator Coil": "蒸发线圈",
    "A flathead screwdriver.": "一字螺丝刀。",
    "A portable jack, used to hold up heavy objects.": "一种便携式千斤顶，用于托起重物。",
    "An evaporator coil, salvaged from an air conditioning unit.": "从空调机组中回收的蒸发器盘管。",
    "It's too dangerous to work on the generator whilst it's active.": "在发电机运作时在上面操作太危险了。",
    ". You'll need to exit the elevator and remove the box from it.": ". 您需要离开电梯，将盒子搬走。",
    "A warning on the panel reads": "面板上的警告写着",
    "Install the mystery box": "安装神秘盒子",
    "Move Box to Network Interface": "将 盒子 移至网络接口",
    "Retrieve Jack": "取回千斤顶",
    "The main central elevator for the installation. With the current level of power, the elevator can go as high as 2F.": "设施的主要中央电梯。 以目前的功率水平，电梯可以上到2层。",
    "The security door to 1> is locked. The box cannot be moved that way.": "通往 1> 的安全门已锁定。 盒子不能向那边移动。",
    "WEIGHT LIMIT EXCEEDED": "超过重量限制",
    "\n            [Hover over the imprints to see their completion requirements.]": "\n [将鼠标悬停在印记上以查看其完成要求。]",
    "A giant screen covers one wall of the room, displaying neural readouts and blueprints of your brain. Most of the details are far too technical for you to understand, but a section towards the left provides two more legible lists - \"Experiences\" and \"Imprints\".": "一个巨大的屏幕覆盖了房间的一面墙，显示了你大脑的神经读数和蓝图。 大多数细节都太技术性了，您无法理解，但是左侧的部分提供了两个更清晰的列表 - “体验”和“印记”。",
    "Calm Mind α": "冷静的头脑α",
    "Consume oxygen at half the normal rate, when idle. (Useless for current content. Sorry!": "闲置时以正常速度的一半消耗氧气。 （对当前内容无用。对不起！",
    "Gold completion: Reactivate life support with only two oxygen tanks.": "金牌完成：仅用两个氧气罐即可重新激活生命维持系统。",
    "Gold completion: Reactivate the life support systems.": "金牌完成：重新激活生命维持系统。",
    "Gold Completion: The 'challenge' way to complete the objective. This will usually require performing something outside of normal progression, and will allow you to access the reward early. If the gold condition is failed/missed, it will appear crossed out in red.": "金牌完成：完成目标的“挑战”方式。 这通常需要在正常进度之外执行一些操作，并且可以让您尽早获得奖励。 如果黄金条件失败/遗漏，它将以红色划掉。",
    "Milestone Gotten!": "获得里程碑！",
    "Neural Imprinting": "神经印迹",
    "NEURAL IMPRINTING": "神经印迹",
    "Neural imprinting": "神经印迹",
    "Regular completion: Currently unimplemented.": "定期完成：目前未实施。",
    "Regular Completion: The 'standard' way to complete the objective. This will [usually? probably always] be linked to a mandatory point of progression.": "定期完成：完成目标的“标准”方式。 这会[通常？ 可能总是] 链接到一个强制性的进展点。",
    "Spare Part?": "零部件？",
    "Tasks consume the same amount of oxygen but complete twice as quickly.": "任务消耗相同数量的氧气，但完成速度是其两倍。",
    "The actual reward is the same either way - by the end of the game you'll have the same rewards, but attempting all-golds could prove a nice additional challenge. [At least, once there are more than two entries in there]": "无论哪种方式，实际奖励都是相同的 - 到游戏结束时，您将获得相同的奖励，但尝试全金牌可能会证明是一个不错的额外挑战。 [至少，一旦那里有两个以上的条目]",
    "The terminal attached to the monitor will allow you select from the available imprints, and by using the connected headset in the centre of the room you can apply them to your own mind, to enhance your mental capabilities.": "连接到显示器的终端将允许您从可用的印记中进行选择，并且通过使用房间中央的连接耳机，您可以将它们应用到您自己的头脑中，以增强您的心理能力。",
    "Time Compression α": "时间压缩α",
    "When the Network Interface (NI) node is unlocked/activated, it will become the Neural Imprinting (NI) node. This node houses a number of 'imprints' (essentially challenges) with quality-of-life gameplay improvements as their rewards.": "当网络接口 (NI) 节点解锁/激活时，它将成为神经印记 (NI) 节点。 该节点包含许多“印记”（本质上是挑战），以提高游戏体验质量作为奖励。",
    "You can hover over an imprint to see [a clue to? it's pretty opaque for now] its completion conditions. Each imprint can be completed one of two ways": "您可以将鼠标悬停在印记上以查看 [线索？ 它现在非常不透明]它的完成条件。 每个印记可以通过以下两种方式之一完成",
    "Alternator": "交流发电机",
    "A heavy steel door. Without power you'll need the jack to hold it open.": "一扇沉重的钢门。 在没有电源的情况下，您需要使用千斤顶使其保持打开状态。",
    "Crowbar": "撬棍",
    "Pry open the door to Decontamination": "撬开净化室大门",
    "Pry open the door to Laboratory": "撬开实验室的门",
    "Remove the jack from the Decontamination door.": "从净化室门下取下千斤顶。",
    "Scientists' Lockers": "科学家的储物柜",
    "The Decontamination room looks much as it did when you arrived. Rows of lockers on either side, and the decontamination units splitting the room in two.\n        The units are open, though, allowing you to pass through without cleaning - probably a safety feature invoked in the evacuation.": "净化室看起来和您到达时一样。 两侧成排的储物柜，净化装置将房间一分为二。\n 不过，这些装置是开放的，允许您无需清洁即可通过——这可能是疏散时调用的安全功能。",
    "Unfortunately, locker #44 - as with most of the lockers on the \"casual side\" - is completely empty. Your flight suit is nowhere to be found.\n        Whether the staff took it to your accommodation, wherever that is, or an opportunistic escapee stole it on their way out, is impossible to say.": "不幸的是，储物柜#44 - 与“休闲一侧”的大多数储物柜一样 - 完全是空的。 你的飞行服无处可寻。\n 是不是工作人员把它带到你的住处，无论在哪里，或者是一个机会主义的逃亡者在他们出去的时候偷走了它，这是不可能的。",
    "The floor in here looks to be extremely damaged, too. Another solid impact and it might give way entirely.": "这里的地板看起来也严重受损。 在一个强大的冲击下，它会让开通路",
    "The reception is desolate. The lack of the receptionist alone makes the room feel like a different place altogether, but the state of the area seals the deal. There's a gaping hole in place of what was the ceiling, and rubble litters the floor.": "接待处很荒凉。 接待员的缺席使房间感觉完全不同，但该地区的状况决定了交易。 天花板上有一个大洞，地上散落着碎石。",
    "A damaged SecLock security door rests against the wall, pried free from the frame.": "一扇损坏的 密码锁 安全门靠在墙上，从框架上撬开。",
    "FLOOR 02 LEFT": "层 02 左",
    "Damaged Locking Mechanism": "损坏的锁装置",
    "Electronic Relay": "电子继电器",
    "An alternator, found alongside the neural imprinting gear.": "与神经印记装置一起发现的交流发电机。",
    "An electronic relay, retrieved from a damaged door lock.": "从损坏的门锁中取出的电子继电器。",
    "The main central elevator for the installation. With the current level of power, the elevator can go as high as 3F.": "安装的主要中央电梯。 以目前的功率水平，电梯可以上到3层。",
    "There's an emergency hatch on the roof of the elevator, but looking through it, you can see the elevator shaft above is blocked. You won't be able to scale further with the ladder.": "电梯顶上有一个应急舱口，但穿过它，你可以看到上面的电梯井被堵住了。 无法伸长梯子更进一步。",
    "Your current clearance (LEVEL 0) is insufficient for this terminal (LEVEL 2).": "您当前的许可 (等级 0) 不足以用于此终端 (等级 2)。",
    "Remove the jack from the Laboratory door.": "从实验室门上取下千斤顶。",
    "It's nearly impossible to tell what research was being conducted here. Any paper records would have been incinerated. One terminal in the far corner looks to be intact, but you have no way of reaching it across the chasm.": "几乎不可能知道这里正在进行什么研究。 任何纸质记录都会被焚毁。 远处角落的一个终端看起来完好无损，但你无法跨越鸿沟到达它。",
    "RUINED LABORATORY": "废弃的实验室",
    "Slide the device over the edge": "将设备从边缘滑过",
    "Slide the device to Decontamination": "将设备滑动到净化室",
    "The door is jacked up - you cannot fit the device through it.": "门被顶起 - 您无法通过它安装设备。",
    "The Lambda Division laboratory is in ruins. Much of the room no longer exists - there's a huge hole in the floor, and various pieces of equipment dangle uselessly from the ceiling above. What does remain is charred black.\n        It looks as though something exploded in this room, quite possibly the same explosion you'd heard on your elevator ride down.": "Lambda分区 实验室已成废墟。 大部分房间已经不复存在——地板上有一个巨大的洞，各种设备无用地悬挂在上面的天花板上。 剩下的是烧焦的黑色。\n看起来这个房间里好像有什么东西爆炸了，很可能和你在乘坐电梯时听到的爆炸一样。",
    "A sticky note attached to the back of the terminal has a series of crossed-out numbers on it, followed by '12345672' Presumably a password of some sort?": "贴在终端背面的便利贴上有一系列划掉的数字，后面是“12345672” 大概是某种密码？",
    "Drop down": "落下",
    "Please swipe an access card to begin.": "请刷门禁卡开始。",
    "SecLock Security Uplift system online.": "密码锁 安全提升系统在线。",
    "SECURITY ROOM": "安保室",
    "The one thing that does seem to still function is a sturdy metal terminal with \"SecLock\" emblazoned down the side of it. A panel on the front allows you to swipe a card and enter a code. The screen blinks incessantly, waiting for some input.": "似乎仍然起作用的一件事是坚固的金属终端，其侧面印有“密码锁”。 前面的面板允许您刷卡并输入代码。 屏幕不停地闪烁，等待一些输入。",
    "The security centre for the installation. Looks like ordinarily four or five employees would be stationed here. One wall is completely covered with monitors - CCTV, perhaps? - but there's nothing on any of the screens, and the controls nearby seem totally unresponsive.": "安装的安全中心。 看样子，这里通常会驻扎四五个员工。 一堵墙完全被监视器覆盖——也许是闭路电视？ - 但任何屏幕上都没有任何东西，而且附近的控件似乎完全没有反应。",
    "There's a gaping hole in the floor now, too, thanks to your handiwork. You can see down into the security room from here.": "多亏你的手艺，现在地板上也有一个大洞。 从这里可以向下看到安全室。",
    "Wrecked Device": "损坏的设备",
    "CLR": "清",
    "ENT": "开",
    "Analysing...": "分析中...",
    "Current authorisation: LEVEL": "当前授权：级别",
    "Voltage Regulator": "稳压器",
    "Authorisation code": "授权码",
    "Checking...": "检查中...",
    "VALID": "有效",
    "Your clearance is now LEVEL": "您的权限现在是 等级",
    "Your current clearance (LEVEL 1) is insufficient for this terminal (LEVEL 1).": "您当前的许可 (等级 1) 不足以用于此终端 (等级 1)。",
    "Move Exosuit to Elevator": "将 强化外骨骼装甲 移至电梯",
    "Move Exosuit to Museum": "将 强化外骨骼装甲 移至博物馆",
    "The sole remaining exhibit is a rather large Exosuit in the centre of the room.Its information panel details the safety benefits of exploring in a metal suit twice your size, but sadly doesn't explain what kind of work such protection would be necessary for.": "唯一剩下的展品是房间中央的一个相当大的 强化外骨骼装甲。它的信息面板详细说明了穿着两倍大的金属套装探索的安全好处，但遗憾的是没有解释这种保护对什么样的工作是必要的。",
    "This wing touts itself as a museum, a monument to the work done at this facility. Unfortunately it's currently a monument to opportunism - almost every exhibit in the room has been taken. That, or the facility's work revolves around empty, damaged displays. The information panels beside the exhibits are powered on, but most simply read \"ERROR\".": "这个侧翼自诩为博物馆，是对在该设施所做工作的纪念碑。 不幸的是，它目前是机会主义的纪念碑——房间里几乎所有的展品都被拿走了。 那，或者说设施的工作围绕着空的、损坏的显示器展开。 展品旁边的信息面板已通电，但大多数只是简单地写着“错误”。",
    ". You'll need to exit the elevator and remove the Exosuit from it.": ". 您需要退出电梯并从中取出 强化外骨骼装甲。",
    "Move Exosuit to Secluded Mountings": "将 强化外骨骼装甲 移到隐蔽的支架上",
    "The central plinth in the room is most conspicuously empty, now you've removed the Exosuit. The four metal claws have retracted into the base.": "房间的中央底座最显眼的是空的，现在你已经移除了 强化外骨骼装甲。 四个金属爪已缩回底座。",
    "Export Save": "导出存档",
    "Mount the Exosuit": "安装强化外骨骼装甲",
    "You've reached the end of current content - congratulations!": "您已到达当前内容的结尾 - 恭喜！",
    "Crack Lock": "破解锁",
    "Retrieve Oxygen Tank": "取回氧气瓶",
    "The lock has been analysed, and can now be opened with the handheld reprogrammer.": "锁已经过分析，现在可以用手持式重新编程器打开。",
    "Analyse Lock": "分析锁",
    "Feed Wires into Vent": "将电线送入通风口",
    "Remove Fuses from Circuit Box": "从电路盒上拆下保险丝",
    "The circuit box for the emergency systems.\n                    The wires from corridor 4 are now touching the sensor, but unpowered.": "应急系统的电路盒。\n 4 号走廊的电线现在正在接触传感器，但没有通电。",
    "The wires have been fed along the vent and are touching the emergency sensor.": "电线已沿通风口送入并接触紧急传感器。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Theme: ": "主题: ",
    "Offline Time": "离线时间",
    "Show Milestones:": "显示的里程碑:",
    "TreeQuest ": "任务树 ",
    "High-Quality Tree:": "高质量树：",
    "Dev Speed:": "开发速度：",
    "Autosave:": "自动保存：",
    "Completed Challenges:": "完成的挑战：",
    "Reach ": "达到 ",
    "Offline Prod:": "离线产出:",
    "It took you ": "这花费了你 ",
    "The Modding Tree ": "模型树",
    "[LIFE SUPPORT RING:": "[生命维持环:",
    "[OXYGEN FULL]": "[氧气充足]",
    "			Time Played: ": "游戏时长:",
    "			Original idea by papyrus (on discord)": "原始创意来自papyrus（在Discord上）",
    "			Changelog": "更新日志",
    "Time played: ": "游戏时长: ",
    "Generator type: ": "发电机类型：",
    "LEVEL 1 authorisation code: ": "一级授权码：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " Fuse Slot": "保险丝槽",
    "TELL ME! [PROLOGUE]": "告诉我![前言]",
    ": Aqua": ": 浅绿色",
    ": Default": ": 默认",
    ": ALWAYS": ": 总是",
    ": AUTOMATION": ": 自动",
    ": INCOMPLETE": ": 部分",
    ": NEVER": ": 从不",
    "HIDDEN": "隐藏",
    "SHOWN": "显示",
    "ON": "开启",
    "OFF": "关闭",
    "/sec": "/秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Find the fusebox key from the scattered items in the corridor.": "从走廊里散落的物品中找到保险丝盒的钥匙。",
    "Note by Jacorb: If anyone wishes to make a mod of this game, that is perfectly fine with me, just make sure to name it something different (ex: Prestige Tree NG+) and to let me know on": "Jacorb的注意事项：如果有人希望制作这个游戏的mod，那对我来说完全没问题，请确保命名不同（例如：Prestige Tree NG +），并让我知道",
    " to beat the game.": " 来获得游戏胜利。",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^Life support in the majority of the facility has failed. You were the poor sap they sent to check out the fault, and whilst you were down here, it gave out entirely.\n(.+)Most of the facility has locked down to buy time for the occupants to evacuate, so you're unable to leave the area.$/, '大部分设施的生命支持都失败了。 你是他们派来检查故障的可怜的树精，而当你在这里的时候，它完全失效了。\n 大部分设施已经锁定，为住户撤离争取时间，所以你无法离开 该地区。'],
    [/^Fortunately, you've managed to barricade yourself in the maintenance room, where the surplus oxygen is stored.\n(.+)There's a small oxygen tank in the room. With that, it should be possible to venture outside, if only for a few seconds at a time before returning to fill up again.$/, '幸运的是，你已经设法把自己挡在了储存多余氧气的维修室里。\n 房间里有一个小氧气罐。 有了这个，应该可以在外面冒险，如果一次只有几秒钟，然后再回来填满。'],
    [/^Unfortunately, the power is also out in most of the surrounding corridor, making it impossible to see, much less use most of the systems. A single light illuminates the north part of the ring.\n(.+)If you can get into the fuse box you may be able to move the light around and explore...and with a little luck, finally repair the life support systems.$/, '遗憾的是，周围走廊的大部分地区也都停电了，无法看到，更不用说使用大部分系统了。 一盏灯照亮了环的北部。\n 如果你能进入保险丝盒，你就可以移动灯来探索……如果运气好的话，最终修复生命维持系统。'],
    [/^ After checking in past the guards, and changing out of your flight suit into your maintenance overalls, the receptionist sent you straight to the service elevator, to check in with the onsite officer in the basement office.. No introduction, no explanation as to where you were or what this company even did.\n(.+)You thought you noticed a hint of urgency in her voice - maybe climate control in the boardroom was on the fritz.$/, '经过保安的检查后，换掉飞行服换上维修工装，接待员直接把你送到服务电梯，到地下室办公室的现场工作人员那里办理登记手续。没有介绍，也没有解释你去了哪里或者公司做了什么。\n你觉得你在她的声音里发现了一丝急迫——也许董事会会议室的气候控制系统出故障了。'],
    [/^ As the elevator descended, what sounded like a rather concerning explosion shook the building. As it approached the bottom,  an odd smell filled the air and it became harder and harder for you to breathe.\n(.+)Pulling your shirt up over your mouth, you darted out of the elevator the moment it reached the bottom. Toxic fumes were billowing into the room, and rubble was everywhere. Anyone who was working down here had presumably managed to flee before the explosion hit.\n(.+)You managed to dive into the maintenance office - which, mercifully, still had clean air inside it - and seal the door behind you, before passing out.$/, '当电梯下降时，听起来像是一声相当令人担忧的爆炸震动了大楼。当它接近底部时，空气中弥漫着一种奇怪的气味，你呼吸起来越来越困难。\n你把衬衫拉起遮住嘴巴，电梯刚到底部，你就冲出了电梯。有毒的烟雾滚滚地进入房间，到处都是碎石。所有在这里工作的人大概都在爆炸发生前逃离了。\n你设法冲进了维修办公室——幸运的是，里面还有干净的空气——然后把身后的门封上了，然后昏倒了。'],
    [/^ Waiting seemed pointless, so you took a look through the schematics in the room. It looks as though the corridor surrounding this room houses the life support system - and if you could get that back online, you'd be able to set up some power generation from the components here.\n(.+)You managed to piece together a basic respirator, and found a portable air tank you could take with you. It'd only let you stay out for a few moments but it should be enough to start working on repairs. Better than waiting for a rescue that might never come.$/, '等待似乎没有意义，所以你看了一下房间里的图纸。看起来好像这个房间周围的走廊里有生命维持系统——如果你能把它恢复在线，你就可以用这里的组件来发电。\n你拼装了一个基本的呼吸器，还找到了一个可以随身携带的便携式氧气罐。它只能让你在外面呆一会儿，但应该足够开始修理了。总比等待可能永远不会到来的救援要好。'],
    [/^ When you came to, you surveyed the room. Most of the systems were offline, but a diagnostic panel was still functioning. From that you got a basic sense of the situation: power and life support to the building had failed after some kind of impact or explosion, and only basic systems were online.\n(.+)The entirety of the staff had evacuated, leaving you alone in a facility you\'d arrived at today...assuming this was even still the same day. To make matters worse, the facility had automatically locked the basement down to contain the issue, and without power lifting the blast doors would be impossible. You were trapped down here.$/, '当你醒过来的时候，你打量了一下房间。大多数系统都离线了，但一个诊断面板仍在工作。从这里你可以了解到基本的情况:建筑物的电力和生命支持系统在某种冲击或爆炸后发生了故障，只有基本的系统还在运行。\n所有的员工都撤离了，只留下你一个人在你今天到达的地方…假设这还是同一天。更糟糕的是，该设施已经自动锁住了地下室，以控制问题，如果没有动力，防爆门是不可能打开的。你被困在这里了。'],
    [/^ "Quality maintenance is hard to find around there." That's apparently all the explanation HQ thought you needed, before shipping you off to a planet you'd never even heard of.\n(.+)Six days later, your ship arrived nose-first a couple of miles from the site after a close shave with an asteroid belt. It's in no state to fly any time soon, but this is a year-long assignment, so you weren't too concerned.\n(.+)You made your way to your residence- and workplace-to-be.$/, '“那里急缺高质量的维修工。”在把你送到一个你闻所未闻的星球之前，总部认为这就是你需要的所有解释。\n六天后，你的飞船在离事发地点几英里的地方与小行星带擦身而过。飞船暂时还不能起飞，还好这项任务长达一年，这使你放下了顾虑。\n你找到了你将来的住处和工作地点。'],
    [/^ Life support in the majority of the facility has failed. You were the poor sap they sent to check out the fault, and whilst you were down here, it gave out entirely.\n(.+)Most of the facility has locked down to buy time for the occupants to evacuate, so you're unable to leave the area.$/, '大部分设施的生命维持系统都失灵了。你是他们派来检查故障的可怜的笨蛋，你在这里的时候，故障完全消失了。\n大部分设施已经封锁，为居民疏散争取时间，所以你无法离开该地区。'],
    [/^ Unfortunately, the power is also out in most of the surrounding corridor, making it impossible to see, much less use most of the systems. A single light illuminates the north part of the ring.\n(.+)If you can get into the fuse box you may be able to move the light around and explore...and with a little luck, finally repair the life support systems.$/, '不幸的是，周围大部分走廊也停电了，让人无法看到，更不用说使用大部分系统了。一盏灯照亮了环的北部。\n如果你能进入保险丝盒，你可能可以移动光周围和探索…运气好的话，最终修复了生命维持系统。'],
    [/^ Fortunately, you've managed to barricade yourself in the maintenance room, where the surplus oxygen is stored.\n(.+)There's a small oxygen tank in the room. With that, it should be possible to venture outside, if only for a few seconds at a time before returning to fill up again.$/, '幸运的是，你已经把自己关在了维护室里，那里储存着多余的氧气。\n房间里有一个小氧气罐。有了它，我们就可以到外面去冒险了，哪怕只有几秒钟的时间，然后再回去填满水。'],
    [/^Controls for the fan in the vent space above.\n(.+)The controls are locked out due to high air toxicity levels.$/, '控制上方排气空间中的风扇。\n由于严重的空气毒性，控制室被封锁在外。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the end of the auxiliary power cable extending from the wall.$/, '$1秒\)\n将从墙上伸出的辅助电源电缆一端拾起。'],
    [/^([\d\.]+) second\)\n(.+)Activate the decontamination system, to clean off anything hazardous from outside the facility.$/, '$1秒\)\n启动净化系统，清除来自设施外的任何危险物质。'],
    [/^([\d\.]+) seconds\)\n(.+)Activate the decontamination system, to clean off anything hazardous from outside the facility.$/, '$1秒\)\n启动净化系统，清除来自设施外的任何危险物质。'],
    [/^([\d\.]+) second\)\n(.+)Activate the decontamination system, to clean off anything hazardous from outside the facility.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n启动净化系统，清除来自设施外的任何危险物质。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Activate the decontamination system, to clean off anything hazardous from outside the facility.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n启动净化系统，清除来自设施外的任何危险物质。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)A key to the main elevator, allowing it to visit the Maintenance basement floor.$/, '$1秒\)\n主电梯的钥匙，允许你访问并维修地下室层。'],
    [/^([\d\.]+) seconds\)\n(.+)A key to the main elevator, allowing it to visit the Maintenance basement floor.$/, '$1秒\)\n主电梯的钥匙，允许你访问维修地下室层。'],
    [/^([\d\.]+) second\)\n(.+)A key to the main elevator, allowing it to visit the Maintenance basement floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n主电梯的钥匙，允许你访问并维修地下室层。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)A key to the main elevator, allowing it to visit the Maintenance basement floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n主电梯的钥匙，允许你访问并维修地下室层。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the first floor.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达一楼。'],
    [/^([\d\.]+) seconds\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the first floor.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达一楼。'],
    [/^([\d\.]+) second\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the first floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达一楼。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the first floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达一楼。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Use the jack to lift the door enough so you can slide under it.$/, '$1秒\)\n使用千斤顶将门抬得足够高，以便您在门下移动。'],
    [/^([\d\.]+) seconds\)\n(.+)Use the jack to lift the door enough so you can slide under it.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n使用千斤顶将门抬得足够高，以便您在门下移动。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room westwards, into the next room.$/, '$1秒\)\n把房间里的大板条箱向西推到隔壁房间。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room westwards, into the next room.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n把房间里的大板条箱向西推到隔壁房间。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room eastwards, into the next room.$/, '$1秒\)\n把房间里的大板条箱向东推到隔壁房间。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room eastwards, into the next room.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n把房间里的大板条箱向东推到隔壁房间。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Search the toolbox and take anything useful.$/, '$1秒\)\n搜索工具箱并获取任何有用的东西。'],
    [/^([\d\.]+) second\)\n(.+)Search the toolbox and take anything useful.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n搜索工具箱并获取任何有用的东西。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove the jack, and allow the door to close.$/, '$1秒\)\n取下千斤顶，让门关闭。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove the jack, and allow the door to close.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n取下千斤顶，让门关闭。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Disassemble the air conditioning unit, and salvage any useful parts.$/, '$1秒\)\n拆卸空调机组，抢救有用的零件。'],
    [/^([\d\.]+) seconds\)\n(.+)Disassemble the air conditioning unit, and salvage any useful parts.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n拆卸空调机组，抢救有用的零件。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)There was an extra part inside the box. It might come in handy elsewhere.$/, '$1秒\)\n盒子里面多了一个零件。 它可能在其他地方派上用场。'],
    [/^([\d\.]+) seconds\)\n(.+)There was an extra part inside the box. It might come in handy elsewhere.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n盒子里面多了一个零件。 它可能在其他地方派上用场。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Search through the lockers and retrieve anything useful.$/, '$1秒\)\n在储物柜中搜索并检索任何有用的东西。'],
    [/^([\d\.]+) seconds\)\n(.+)Search through the lockers and retrieve anything useful.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n在储物柜中搜寻有用的东西。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Replace the burnt-out relay in the generator..$/, '$1秒\)\n更换发电机中烧坏的继电器..'],
    [/^([\d\.]+) seconds\)\n(.+)Replace the burnt-out relay in the generator..\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n更换发电机中烧坏的继电器..\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the door to the passage east of 3F. LEVEL 2 authorisation is required.$/, '$1秒\)\n带有刷卡槽的密码锁安全终端，控制通往3层东侧通道的门。 需要 2 级授权。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the door to the passage east of 3F. LEVEL 2 authorisation is required.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n带有刷卡槽的密码锁安全终端，控制通往3层东侧通道的门。 需要 2 级授权。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the third floor.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达三楼。'],
    [/^([\d\.]+) seconds\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the third floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达三楼。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room westwards, into the elevator.$/, '$1秒\)\n将房间里的大板条箱向西推入电梯。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large crate in the room westwards, into the elevator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将房间里的大板条箱向西推入电梯。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the box towards the network interface - the holes in the box match the plug there.$/, '$1秒\)\n将框拖向网络接口 - 框中的孔与那里的插头相匹配。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the box towards the network interface - the holes in the box match the plug there.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将框拖向网络接口 - 框中的孔与那里的插头相匹配。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large device in the room westwards, over the edge of the hole.$/, '$1秒\)\n将房间里的大设备向西推，越过洞的边缘。'],
    [/^([\d\.]+) seconds\)\n(.+)Push the large device in the room westwards, over the edge of the hole.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将房间里的大设备向西推，越过洞的边缘。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)The wire has jammed the overhead fan above Corridor 1. It'll take a little longer to feed it through.$/, '$1秒\)\n电线卡住了走廊 1 上方的吊扇。需要更长的时间才能通过它。'],
    [/^([\d\.]+) seconds\)\n(.+)The wire has jammed the overhead fan above Corridor 1. It'll take a little longer to feed it through.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n电线卡住了走廊 1 上方的吊扇。需要更长的时间才能通过它。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Feed the unpowered wires along the overhead vent.$/, '$1秒\)\n将未通电的电线沿着头顶通风口送入。'],
    [/^([\d\.]+) seconds\)\n(.+)Feed the unpowered wires along the overhead vent.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将未通电的电线沿着头顶通风口送入。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Transfer the Model #### Exosuit onto the mountings, allowing for charging and repairs.$/, '$1秒\)\n将#### 型强化外骨骼装甲转移到支架上，以便充电和维修。'],
    [/^([\d\.]+) seconds\)\n(.+)Transfer the Model #### Exosuit onto the mountings, allowing for charging and repairs.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将#### 型强化外骨骼装甲转移到支架上，以便充电和维修。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit eastwards, into the museum.$/, '$1秒\)\n将强化外骨骼装甲向东拖动，进入博物馆。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit eastwards, into the museum.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将强化外骨骼装甲向东拖动，进入博物馆。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit westwards, into the 2F Elevator.$/, '$1秒\)\n将强化外骨骼装甲向西拖动，进入 2层 电梯。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit westwards, into the 2F Elevator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将强化外骨骼装甲向西拖动，进入 2层 电梯。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drop down the hole in the floor, into the security room.$/, '$1秒\)\n跳进地板上的洞，进入安保室。'],
    [/^([\d\.]+) seconds\)\n(.+)Drop down the hole in the floor, into the security room.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n跳进地板上的洞，进入安保室。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Salvage parts from the now-useless device you dropped through the ceiling.$/, '$1秒\)\n从那些从天花板上掉下来，暂时派不上用场的设备上打捞零件。'],
    [/^([\d\.]+) seconds\)\n(.+)Salvage parts from the now-useless device you dropped through the ceiling.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n从那些从天花板上掉下来，暂时派不上用场的设备上打捞零件。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Crack the lock open using the reprogrammer's bypass codes.$/, '$1秒\)\n使用重编程器的绕过代码破解锁。'],
    [/^([\d\.]+) seconds\)\n(.+)Crack the lock open using the reprogrammer's bypass codes.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n使用重编程器的绕过代码破解锁。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit westwards, into the next room.$/, '$1秒\)\n将 强化外骨骼装甲 向西拖到下一个房间。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit westwards, into the next room.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将 强化外骨骼装甲 向西拖到下一个房间。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit towards the maintenance mountings.$/, '$1秒\)\n将强化外骨骼装甲拖向维护支架。'],
    [/^([\d\.]+) seconds\)\n(.+)Drag the exosuit towards the maintenance mountings.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将强化外骨骼装甲拖向维护支架。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Analyse the lock data and create a breaker code.$/, '$1秒\)\n分析锁数据并创建断路器代码。'],
    [/^([\d\.]+) seconds\)\n(.+)Analyse the lock data and create a breaker code.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n分析锁数据并创建断路器代码。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the lock on the displays. LEVEL 1 authorisation is required.$/, '$1秒\)\n带有刷卡槽的 密码锁 安全终端，控制显示器上的锁。 需要 1 级授权。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the lock on the displays. LEVEL 1 authorisation is required.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n带有刷卡槽的 密码锁 安全终端，控制显示器上的锁。 需要 1 级授权。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the door to the Security Room. LEVEL 1 authorisation is required.$/, '$1秒\)\n带有刷卡槽的 密码锁 安全终端，控制通往安全室的门。 需要 1 级授权。'],
    [/^([\d\.]+) seconds\)\n(.+)A SecLock security terminal with a card swipe slot, controlling the door to the Security Room. LEVEL 1 authorisation is required.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n带有刷卡槽的 密码锁 安全终端，控制通往安全室的门。 需要 1 级授权。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the evaporator coil in the generator.$/, '$1秒\)\n将蒸发器盘管安装在发电机中。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the evaporator coil in the generator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将蒸发器盘管安装在发电机中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the alternator into the generator.$/, '$1秒\)\n将交流发电机安装到发电机中。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the alternator into the generator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将交流发电机安装到发电机中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the mysterious box found upstairs. It seems like it slots right into place here.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n安装楼上发现的神秘盒子。 它似乎刚好能插入这里。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the mysterious box found upstairs. It seems like it slots right into place here.$/, '$1秒\)\n安装楼上发现的神秘盒子。 它似乎刚好能插入这里。'],
    [/^([\d\.]+) second\)\n(.+)Your new ID card, confirming your status as a new maintenance employee.$/, '$1秒\)\n您的新身份证，确认您作为新维修员工的身份。'],
    [/^([\d\.]+) seconds\)\n(.+)Your new ID card, confirming your status as a new maintenance employee.$/, '$1秒\)\n您的新身份证，确认您作为新维修员工的身份。'],
    [/^([\d\.]+) second\)\n(.+)Your new ID card, confirming your status as a new maintenance employee.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n您的新身份证，确认您作为新维修员工的身份。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Your new ID card, confirming your status as a new maintenance employee.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n您的新身份证，确认您作为新维修员工的身份。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove the fuses from the emergency system.$/, '$1秒\)\n从应急系统上拆下保险丝。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove the fuses from the emergency system.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n从应急系统上拆下保险丝。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Reach into the open vent and grab the oxygen tank.$/, '$1秒\)\n伸手进入打开的通风口并抓住氧气罐。'],
    [/^([\d\.]+) seconds\)\n(.+)Reach into the open vent and grab the oxygen tank.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n伸手进入打开的通风口并抓住氧气罐。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the second floor.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达二楼。'],
    [/^([\d\.]+) second\)\n(.+)Raise the emergency ladder attached to the lift, which you can scale to reach the second floor.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n升起安装在电梯上的紧急梯子，您可以将其展开以到达三楼。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Disassemble the remnants of the lock and retrieve any useful parts.$/, '$1秒\)\n拆开锁的残余物并取回任何有用的部件。'],
    [/^([\d\.]+) seconds\)\n(.+)Disassemble the remnants of the lock and retrieve any useful parts.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n拆开锁的残余物并取回任何有用的部件。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Use the crowbar to force open the broken door.$/, '$1秒\)\n使用撬棍强行打开破损的门。'],
    [/^([\d\.]+) second\)\n(.+)Use the crowbar to force open the broken door.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n使用撬棍强行打开破损的门。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Install the rotary motor into the generator.$/, '$1秒\)\n将旋转电机安装到发电机中。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the rotary motor into the generator.$/, '$1秒\)\n将旋转电机安装到发电机中。'],
    [/^([\d\.]+) second\)\n(.+)Install the rotary motor into the generator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将旋转电机安装到发电机中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Install the rotary motor into the generator.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n将旋转电机安装到发电机中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the jack from the open doorway.$/, '$1秒\)\n从敞开的门口拿起千斤顶。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the jack from the open doorway.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n从敞开的门口拿起千斤顶。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Use the elevator key, to activate the button for the basement floor..$/, '$1秒\)\n使用电梯钥匙，激活地下室的按钮。'],
    [/^([\d\.]+) seconds\)\n(.+)Use the elevator key, to activate the button for the basement floor..$/, '$1秒\)\n使用电梯钥匙，激活地下室的按钮。'],
    [/^([\d\.]+) second\)\n(.+)Use the elevator key, to activate the button for the basement floor..\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n使用电梯钥匙，激活地下室的按钮。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Use the elevator key, to activate the button for the basement floor..\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n使用电梯钥匙，激活地下室的按钮。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)An upright fan that's seen better days. You should be able to salvage the rotary motor from it.$/, '$1秒\)\n一个曾一度良好运作的直立风扇。 您应该能够从中抢救出旋转电机。'],
    [/^([\d\.]+) seconds\)\n(.+)An upright fan that's seen better days. You should be able to salvage the rotary motor from it.$/, '$1秒\)\n一个曾一度良好运作的直立风扇。 您应该能够从中抢救出旋转电机。'],
    [/^([\d\.]+) second\)\n(.+)An upright fan that's seen better days. You should be able to salvage the rotary motor from it.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n一个曾一度良好运作的直立风扇。 您应该能够从中抢救出旋转电机。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)An upright fan that's seen better days. You should be able to salvage the rotary motor from it.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n一个曾一度良好运作的直立风扇。 您应该能够从中抢救出旋转电机。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Put on the maintenance uniform provided for you.$/, '$1秒\)\n穿上为您提供的维修制服。'],
    [/^([\d\.]+) seconds\)\n(.+)Put on the maintenance uniform provided for you.$/, '$1秒\)\n穿上为您提供的维修制服。'],
    [/^([\d\.]+) second\)\n(.+)Put on the maintenance uniform provided for you.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n穿上为您提供的维修制服。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Put on the maintenance uniform provided for you.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n穿上为您提供的维修制服。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) second\)\n(.+)Remove your flight suit and stow it in the locker.$/, '$1秒\)\n脱下飞行服并将其存放在储物柜中。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove your flight suit and stow it in the locker.$/, '$1秒\)\n脱下飞行服并将其存放在储物柜中。'],
    [/^([\d\.]+) second\)\n(.+)Remove your flight suit and stow it in the locker.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n脱下你的飞行服并将其存放在储物柜中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove your flight suit and stow it in the locker.\n(.+)Time remaining: (.+) seconds.$/, '$1秒\)\n脱下你的飞行服并将其存放在储物柜中。\n 剩余时间：$4 秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Bypass the anti-tamper system on the southern wall panels.$/, '$1秒\)\n绕过南部墙板上的防篡改系统。'],
    [/^([\d\.]+) seconds\)\n(.+)Open the electromagnetic vents in the corridors east and west of the maintenance room.$/, '$1秒\)\n打开维护室东西两侧走廊的电磁通风口。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove a fuse from a damaged wall panel.$/, '$1秒\)\n从损坏的墙板上拆下保险丝。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the handheld lock reprogrammer terminal.$/, '$1秒\)\n拿起手持锁重编程器终端。'],
    [/^([\d\.]+) seconds\)\n(.+)Pick up the handheld lock reprogrammer terminal.$/, '$1秒\)\n拿起手持锁重编程器终端。'],
    [/^([\d\.]+) seconds\)\n(.+)Scan the lock with the handheld reprogrammer.$/, '$1秒\)\n用手持式重编程器扫描锁。'],
    [/^([\d\.]+) seconds\)\n(.+)Damage to the wall has exposed live wiring. You could \(carefully\) pull it out some distance.$/, '$1秒\)\n墙上的损坏使带电电线露出来了。你可以\(小心地\)把它拉出一段距离。'],
    [/^([\d\.]+) seconds\)\n(.+)Repair the electronic and life support circuits in this corridor.$/, '$1秒\)\n修复这条走廊的电子和生命维持电路。'],
    [/^([\d\.]+) seconds\)\n(.+)Find the fusebox key from the scattered items in the corridor.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n从走廊散落的物品中找到保险丝盒的钥匙。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Repair the electronic and life support circuits in this corridor.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n修复这条走廊的电子和生命维持电路。\n剩余时间: $4秒。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the end of the auxiliary power cable extending from the wall.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n将从墙上伸出的辅助电源电缆一端拾起。\n剩余时间: $4秒。'],
    [/^([\d\.]+) second\)\n(.+)Pick up the handheld lock reprogrammer terminal.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n拿起手持锁重编程器终端。\n剩余时间: $4秒。'],
    [/^([\d\.]+) second\)\n(.+)Scan the lock with the handheld reprogrammer.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n用手持式重编程器扫描锁。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Scan the lock with the handheld reprogrammer.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n用手持式重编程器扫描锁。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Pick up the handheld lock reprogrammer terminal.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n拿起手持锁重编程器终端。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove a fuse from the southern wall panel.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n从南墙板上拆下保险丝。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove a fuse from the southern wall panel.$/, '$1秒\)\n从南墙板上拆下保险丝。'],
    [/^([\d\.]+) seconds\)\n(.+)Remove a fuse from a damaged wall panel.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n从损坏的墙板上拆下保险丝。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Bypass the anti-tamper system on the southern wall panels.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n绕过南部墙板上的防篡改系统。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Open the electromagnetic vents in the corridors east and west of the maintenance room.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n打开维护室东西两侧走廊的电磁通风口。\n剩余时间: $4秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Disable the automatic filtration system.\n(.+)Life support is broken anyway, so what\'s the harm\?\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n关闭自动过滤系统。\n反正生命维持系统也坏了，又有什么害处呢?\n剩余时间: $5秒。'],
    [/^([\d\.]+) seconds\)\n(.+)Disable the automatic filtration system.\n(.+)Life support is broken anyway, so what\'s the harm\?$/, '$1秒\)\n关闭自动过滤系统。\n反正生命维持系统也坏了，又有什么害处呢?'],
    [/^([\d\.]+) seconds\)\n(.+)Damage to the wall has exposed live wiring. You could \(carefully\) pull it out some distance.\n(.+)Time remaining: ([\d\.]+) seconds.$/, '$1秒\)\n墙上的损坏使带电电线露出来了。你可以\(小心地\)把它拉出一段距离。\n剩余时间: $4秒。'],
    [/^Place fuses in the slots to provide power to that section of the corridor.\n(.+)Removing a fuse may revert certain changes.$/, '在槽里放上保险丝，为走廊的那部分供电。\n拆卸保险丝可能会恢复某些更改。'],
    [/^You have (.+) fuses available \((.+) total\).$/, '你有$1个可用的保险丝\(共$2个\)。'],
    [/^Corridor circuit repaired. If the corridor loses power, the circuit will break.\n(.+)Circuit components repaired: (.+)\/$/, '走廊电路修好了。如果走廊断电，电路就会断路。\n电路部件维修: $2\/'],
    [/^You are holding the power cable in your hand.\n(.+)The spring-loaded winch will retract it if you drop it.$/, '你手里拿着的是电力电缆。\n如果它被丢下，弹簧绞车会将其收回。'],
    [/^(\d+) fuse\n(.+)Turns off the lights in corridor (\d+).$/, '$1 保险丝\n关闭$3号走廊的灯。'],
    [/^(\d+) fuse\n(.+)Turns on the lights in Corridor (\d+).$/, '$1 保险丝\n打开$3号走廊的灯。'],
    [/^You have (.+) fuse available \((.+) total\).$/, '你有 $1 个可用的保险丝\(共$2个\)。'],
    [/^A base station for reprogramming electronic locks.\n(.+)The handheld scanner and unlocker appears to be missing.$/, '为电子锁重新编程的基站。\n手持扫描仪和解锁器似乎失踪了。'],
    [/^The circuit box for the emergency systems.\n(.+)Should unlock if the sensor in the vents is shorted out.$/, '应急系统的电路箱。\n如果通风口中的传感器短路，则应解锁。'],
    [/^The filtration system has been overridden.\n(.+)Safety locks on fan controls are disabled.$/, '过滤系统被破坏了。\n风扇控制的安全锁被禁用。'],
    [/^An auxiliary power inlet connected to the maintenance terminal in Corridor 6.\n(.+)Perhaps there's a cable you can use nearby.$/, '辅助电源入口连接到6号走廊维护终端。\n也许附近有可用的电缆。'],
    [/^The overhead vent is damaged here.\n(.+)It runs across the north wall, towards Corridor 8.$/, '上面的通风口这里损坏了。\n它穿过北墙，通向8号走廊。'],
    [/^A base station for reprogramming electronic locks.\n(.+)If you scan a lock, you can analyse it here.$/, '为电子锁重新编程的基站。\n如果你扫描一个锁，你可以在这里分析它。'],
    [/^A closet containing spare electrical components. The lock resets whenever the power is cycled.\n(.+)Your reprogrammer has scanned the lock and is ready for analysis.$/, '装有备用电器元件的壁橱。每当电源循环时，锁就会重置。↵您的重新编程人员已经扫描了锁并准备好进行分析。'],
    [/^([\d\.]+) fuses, all ([\d\.]+) of which are in use.$/, '$1个保险丝，$2个都在使用中。'],
    [/^Cost: (.+) power\n(.+)$/, '成本：$1 能量'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^You have (.+) fuses remaining.$/, '您还剩 $1 个保险丝。'],
    [/^(\d+) seconds\)\n                    $/, '$1 秒)\n                    '],
    [/^g(\d+): ([\d\.]+) power \(([\d\.]+)\% efficiency$/, 'g$1：$2 功率（$1\% 效率'],
    [/^g(\d+): ([\d\.]+) power \(Power \-$/, 'g$1：$2 功率（功率 \-'],
    [/^g(\d+): ([\d\.]+) power \(Power \+([\d\.]+), then \*$/, 'g$1：$2 功率（功率 \+$3, 然后 \*'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^(\d+)F EAST--\>$/, '$1F 东--\>'],
    [/^\<--(\d+)F WEST$/, '\<--$1F 西'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);